# Generated by Django 3.0.5 on 2020-04-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_auto_20200410_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
