# Generated by Django 3.0.5 on 2020-04-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_auto_20200412_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
