# Generated by Django 3.0.5 on 2020-04-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_lesson_lesson_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='Module',
            new_name='module',
        ),
    ]
