# Generated by Django 3.0.5 on 2020-04-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_auto_20200412_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='eng_tag',
            field=models.CharField(max_length=200, verbose_name='Английский тег'),
        ),
    ]
